#!/bin/bash
. ./bash_lib

echo "building..."

# dependencies
# inspired by https://github.com/LibVNC/libvncserver/blob/master/.travis.yml
# and cmake messages about missing png/jpeg libs...
# as well as various possible crypto libraries, though it is probably far
# preferable to handle encryption and authorization through tunneling 
# on a separate layer!
if ! test -f ./_dependencies_where_installed ; then
    sudo apt-get update
    sudo apt-get --assume-yes \
        --no-install-suggests \
        --no-install-recommends \
        install \
            libsdl2-dev \
            liblzo2-dev \
            gnutls-dev \
            libgcrypt-dev \
            libssl-dev \
            libpng-dev \
            libjpeg-dev
    touch _dependencies_where_installed
fi

# fetch submodules
if ! test -f ./webclients/novnc/vnc.html ; then
    git submodule init
    git submodule update
fi

(
# build steps from ORIGINAL.README.md, except mkdir -p build so that build existing is not a problem [[
mkdir -p build
cd build
cmake ..
cmake --build .
# ]]
)

# to make example's http server work, 
#  rfbScreen->httpDir = "../webclients";
# must exist, which, if you cd into ./build/examples should be at
#   ./build/examples/../webclients = ./build/webclients
if ! test -d "./build/webclients" ; then
    ln -s "$(realpath ./webclients)" "./build/webclients"
fi

echo "built."
