#!/bin/bash
. ./bash_lib

./build-it

cd ./build/examples

echo "Will run tcp:vnc protocol server/screen on TCP port 5900 and tcp:http protocol server at 5800 hosting novnc websockify webbrowser js/client"
echo "vnc://localhost:5900"
echo "http://localhost:5800"
#./example
./simple
